#!/usr/bin/env node
const cp = require('child_process');
const {promisify} = require('util');
const execAsync = promisify(cp.exec);

function reject () {
  console.error('Verification failed. Please fix all errors and warnings and retry.');
  process.exit(1);
}

function accept () {
  console.error('Push validated ✓');
  process.exit(0);
}

async function verifyPush () {
  process.stdout.write('Verifying git flags... ');
  const result = await execAsync('git config --global pull.rebase', null);
  if (result.stdout.trim() !== 'true') {
    console.log('✗');
    console.log('Your pull.rebase setting is wrong. Please run the following command:\n');
    console.log('git config --global pull.rebase true\n');
    reject();
  }
  console.log('✓');

  accept();
}

verifyPush();
